### ISSUE TITLE
Undefined method in Guzzle?

### ISSUE THREAD

**Issue by daniert** [jayzeng/virustotal_apiwrapper#22] opened 2017-01-25 13:21 UTC
I'm getting this error:

PHP Fatal error:  Call to undefined method GuzzleHttp\Psr7\Response::send() in ..../vendor/jayzeng/virustotalapi/Src/VirusTotal/File.php on line 25

("guzzlehttp/guzzle": "^6.2")

**Comment by jayzeng** [comment] 2017-01-26 00:43
I think I see what the problem is, @daniert do you mind putting the file you want to scan somewhere?

**Comment by daniert** [comment] 2017-01-26 12:27
No problem, but I tried with several files and I got the same error. Anyway, I've attached the file in this message.
[filetest.apk.zip](https://github.com/jayzeng/virustotal_apiwrapper/files/732208/filetest.apk.zip)

**Comment by tw88** [comment] 2017-01-27 15:51
I get the same error. Any news on this?

**Comment by jayzeng** [comment] 2017-01-27 16:50
I will put in a fix later tonight, sorry for the delay guys

**Comment by jayzeng** [comment] 2017-01-29 06:26
@daniert @tw88 I pushed the fix to 0.1.9 (https://packagist.org/packages/jayzeng/virustotalapi#0.1.9), please bump up compose.json to this version and let me know how it goes

**Comment by daniert** [comment] 2017-01-30 09:50
It works perfectly for me, thank you!

**Comment by jayzeng** [comment] 2017-01-30 19:01
:) Going to close this issue, feel free to re-open if it remains unresolved.

**Closed by jayzeng** 2017-01-30 19:01 UTC
